### PR TITLE
Fix: Bootstrap sizes should be a registered type

### LINKED ISSUE #339: Bootstrap sizes should be a registered type
Bootstrap sizes like `'xs' | 'sm' | 'md' | 'lg'` are used and defined in multiple files. This should be separated into a BootstrapSize type defined in one place.

### PR DESCRIPTION
**Pull request by gidomanders**
Bootstrap sizes like 'xs' | 'sm' | 'md' | 'lg' are used and defined in
multiple files. This should be separated into a BootstrapSize type
defined in one place.

Closes #339

### CODE REVIEW

File: src/utilities/size/size.ts [hunk 1]
```diff
@@ -0,0 +1 @@
+export type BootstrapSize = 'xs' | 'sm' | 'md' | 'lg';
```
Comment (MrHus) [inline src/utilities/size/size.ts]: Belongs in core/types.ts

**Comment by MrHus** [comment]
The SubmitButton and Button have `size` props as well.
