### PR TITLE
fix: pagination clicking page triggers form submit

### LINKED ISSUE #702: Pagination triggers a form submit when used in forms
When the Pagination component is used inside a form, clicking a page number triggers a form submit if no rerender is triggered.

### PR DESCRIPTION
**Pull request by BarryS42**
When used in a form, the pagination triggers a form submit.

Changed pagination links to be buttons with type button instead of the 
default submit.

Closes #702

### CODE REVIEW

File: src/core/Pagination/Pagination.tsx [hunk 1]
```diff
@@ -125,7 +125,7 @@ export function Pagination<T>({
                 {item}
               </PaginationLink>
             ) : (
-              <PaginationLink onClick={() => onChange(item)}>
+              <PaginationLink onClick={() => onChange(item)} disabled = {item === current}>
```
Comment (gidomanders) [inline src/core/Pagination/Pagination.tsx:128]: Spaces around the `=` character should be removed

**Review by gidomanders — CHANGES_REQUESTED** [review]

**Review by gidomanders — APPROVED** [review]
