### PR TITLE
Fix: Type integrity

### LINKED ISSUE #335: Bug: Type integrity
In Addon, you can specify icon and text without warning. If you add `text?: never` to IconProps, you'll get a warning that icon and text cannot be used together.

### PR DESCRIPTION
**Pull request by gidomanders**
In Addon, you can specify icon and text without warning.
Added `text?: never` to IconProps and `icon?: never` to TextProps so
you'll get a warning that icon and text cannot be used together.
Did the same with ConfirmButton where icon and children should never be
`undefined`, they either have a valid value or they're not specified at
all.

Closes #335

### CODE REVIEW

File: src/core/ConfirmButton/ConfirmButton.tsx [hunk 1]
```diff
@@ -131,19 +133,34 @@ export default function ConfirmButton({
     onConfirm(event);
   }
 
+  function getButton() {
+    const buttonProps = {
+      onClick: openModal,
+      color,
+      inProgress: !!inProgress
```
Comment (MrHus) [inline src/core/ConfirmButton/ConfirmButton.tsx]: Can't you just add `children` and `icon` to button props somehow. This way you don't need any
if statement in getButton.

Comment (gidomanders) [reply src/core/ConfirmButton/ConfirmButton.tsx]: Ignoring the type-safety error with icon and children in Props, I could remove the entire function. Maybe not the ideal situation as I have to ts-ignore, which could cause other problems in the future, but I can't think of another way to solve this without if statements.

File: src/core/ConfirmButton/ConfirmButton.tsx [hunk 2]
```diff
@@ -131,19 +133,23 @@ export default function ConfirmButton({
     onConfirm(event);
   }
 
+  // @ts-ignore
```
Comment (MrHus) [inline src/core/ConfirmButton/ConfirmButton.tsx]: Can you fix this using my solution I've chatted you.
