### PR TITLE
fix: DisplayValues type in ModalPickerSingle

### LINKED ISSUE #438: ModalPicker single and multiple displayValues type is wrong
Currently they both share the following DisplayValues type:

`DisplayValues<T> = (values?: T | T[] | React.ReactNode) => React.ReactNode;`

This is wrong:

ModalPickerSingle should have:

`(values?: T) => React.ReactNode;`

And multiple should have:

`values?: T[]) => React.ReactNode;`

The type should not be shared!

### PR DESCRIPTION
**Pull request by gidomanders**
The ModalPickerSingle doesn't have multiple selected values, so
when specifying displayValues you should not have to deal with a
multi-value type.

Added a DisplayValue type that only deals with a single value.

Closes #438

### CODE REVIEW

File: src/form/ModalPicker/multiple/ModalPickerMultiple.tsx [hunk 1]
```diff
@@ -17,10 +17,11 @@ import {
...
   RenderOptionsOption
 } from '../../option';
-import {
-  DisplayValues,
-  ModalPickerOpener
-} from '../ModalPickerOpener/ModalPickerOpener';
+import { ModalPickerOpener } from '../ModalPickerOpener/ModalPickerOpener';
+
+export type DisplayValues<T> = (
+  values?: T[] | React.ReactNode
```
Comment (MrHus) [inline src/form/ModalPicker/multiple/ModalPickerMultiple.tsx:23]: Remove the React.ReactNode.

File: src/form/ModalPicker/single/ModalPickerSingle.tsx [hunk 2]
```diff
@@ -16,10 +16,9 @@ import {
   RenderOptions,
   RenderOptionsOption
 } from '../../option';
-import {
-  DisplayValues,
-  ModalPickerOpener
-} from '../ModalPickerOpener/ModalPickerOpener';
+import { ModalPickerOpener } from '../ModalPickerOpener/ModalPickerOpener';
+
+export type DisplayValue<T> = (values?: T | React.ReactNode) => React.ReactNode;
```
Comment (MrHus) [inline src/form/ModalPicker/single/ModalPickerSingle.tsx:21]: Remove the React.ReactNode.
