### PR TITLE
fix: CheckboxMultipleSelect columns have static width

### LINKED ISSUE #552: CheckboxMultipleSelect columns have static width
In the CheckboxMultipleSelect, the columns have a static width. When the component is used in smaller layouts, the component overlays the elements next to it due to the static width.

### PR DESCRIPTION
**Pull request by gidomanders**
In the CheckboxMultipleSelect, the columns have a static width. When the
component is used in smaller layouts, the component overlays the
elements next to it due to the static width.

Added max-width 100% to prevent out-of-bounds display.
Removed chunking to prevent loads of whitespace when the number of
options is just over 10. The developer implementing this component is 
now responsible for the grid.

Closes #552

### CODE REVIEW

File: src/form/CheckboxMultipleSelect/CheckboxMultipleSelect.tsx [hunk 1]
```diff
@@ -168,18 +168,8 @@ export default function CheckboxMultipleSelect<T>(props: Props<T>) {
...
-        <Row>
-          {chunks.map((options, index) => {
-            return (
-              <Col xs="auto" key={index} style={{ width: '300px' }}>
-                {renderOptions({ options, horizontal: false })}
-              </Col>
-            );
-          })}
-        </Row>
+        <Row>{renderOptions({ options: page.content, horizontal: false })}</Row>
```
Comment (MrHus) [inline src/form/CheckboxMultipleSelect/CheckboxMultipleSelect.tsx:172]: The commit message speaks of decreasing chunk size, but you have removed them completely.
Please update the commit message.

File: src/form/CheckboxMultipleSelect/CheckboxMultipleSelect.tsx [hunk 2]
```diff
@@ -203,19 +193,26 @@ export default function CheckboxMultipleSelect<T>(props: Props<T>) {
...
-              value={index}
-              disabled={!isOptionEnabled(option)}
-              onChange={() => optionClicked(option, isSelected)}
-            />{' '}
-            {label}
-          </Label>
+          {checkbox}
         </FormGroup>
+      ) : (
+        <Col xs="auto" key={key} style={{ width: '300px', maxWidth: '100%' }}>
```
Comment (MrHus) [inline src/form/CheckboxMultipleSelect/CheckboxMultipleSelect.tsx:213]: I wonder if the `300px` is still needed?

**Review by MrHus — CHANGES_REQUESTED** [review]

File: src/form/CheckboxMultipleSelect/CheckboxMultipleSelect.tsx (hunk 2 above)
Comment (gidomanders) [reply src/form/CheckboxMultipleSelect/CheckboxMultipleSelect.tsx:213]: Yes, without the width the checkboxes are all over the place.

**Review by MrHus — APPROVED** [review]
